CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "projects" ("id" integer primary key autoincrement not null, "is_published" tinyint(1) not null default '0', "project_thumb" varchar not null, "title" varchar not null, "description" varchar not null, "content" text not null, "project_url" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "blogs" ("id" integer primary key autoincrement not null, "is_published" tinyint(1) not null default '0', "blog_thumb" varchar not null, "title" varchar not null, "description" varchar not null, "content" text not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "experiences" ("id" integer primary key autoincrement not null, "date_start" date not null, "date_end" date not null, "description" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "profiles" ("id" integer primary key autoincrement not null, "name" varchar not null, "job" varchar not null, "content" text not null, "img_profile" varchar not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "skills" ("id" integer primary key autoincrement not null, "img_skill" varchar not null, "text_primary" varchar not null, "text_secondary" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO migrations VALUES(73,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(74,'2014_10_12_100000_create_password_reset_tokens_table',1);
INSERT INTO migrations VALUES(75,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(76,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(77,'2023_04_29_200828_create_projects_table',1);
INSERT INTO migrations VALUES(78,'2023_04_29_201120_create_blogs_table',1);
INSERT INTO migrations VALUES(79,'2023_05_01_230235_create_experiences_table',1);
INSERT INTO migrations VALUES(80,'2023_05_02_104845_create_profiles_table',1);
INSERT INTO migrations VALUES(81,'2023_05_02_111836_create_skills_table',1);
